kind: Job
apiVersion: batch/v1
metadata:
  name: monitor14
  namespace: monitoring
  labels:
    app: monitor
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitor
    spec:
      containers:
        - name: container-qsdbem
          image: 'harbor.wns8.io/devops/domain-check-expiry:v1.0.4-optimize12'
          env:
            - name: DAY_TO_CHECK_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: monitor
                  key: DAY_TO_CHECK_EXPIRY
            - name: MAX_RETRY
              valueFrom:
                configMapKeyRef:
                  name: monitor
                  key: MAX_RETRY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: monitor
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                configMapKeyRef:
                  name: monitor
                  key: TELEGRAM_CHAT_ID
            - name: LIMIT_DAY_TO_CHECK
              valueFrom:
                configMapKeyRef:
                  name: monitor
                  key: LIMIT_DAY_TO_CHECK
          resources:
            requests:
              cpu: 0.01
              memory: 50Mi
            limits:
              cpu: 2
              memory: 7G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: domain-checker-sa
      serviceAccount: domain-checker-sa
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false
